import type { SupabaseClient } from '@supabase/supabase-js'
import type { StatusState } from '@goutatou/db'
import { createAutoStatusRepo } from './repo.js'

export interface ApprovalStatusRow {
  id: string
  restaurantId: string
  state: StatusState
  autoGenerated: boolean
  content: string
  mediaUrl: string | null
}

/** Plat choisi pour une régénération, avec sa position dans la rotation (utilisée comme templateIndex). */
export interface NextApprovalDish {
  name: string
  price: number
  photoUrl: string
  index: number
}

export interface ApprovalRepo {
  /**
   * Lecture SÉCURISÉE : filtre `restaurant_id` dans la requête même (pas de check applicatif
   * après coup) — aucune validation croisée entre restaurants n'est possible. `null` si le
   * statut n'existe pas ou appartient à un autre restaurant que celui du canal.
   */
  getStatus(statusId: string, restaurantId: string): Promise<ApprovalStatusRow | null>
  /** Passe en 'scheduled' UNIQUEMENT si l'état courant est 'pending_approval'. Renvoie le succès. */
  approve(statusId: string): Promise<boolean>
  /** Passe en 'canceled' + error FR, uniquement depuis 'pending_approval'. */
  cancel(statusId: string): Promise<boolean>
  /** Remplace content/media_url, reste 'pending_approval' (garde côté requête, pas seulement processor). */
  regenerate(statusId: string, content: string, mediaUrl: string): Promise<boolean>
  /**
   * Plat suivant le plat courant (mediaUrl actuel) dans la rotation des plats disponibles avec
   * photo — même lecture que le flux de génération auto (cf. autostatus/repo.ts getPhotoDishes),
   * réutilisée en LECTURE SEULE ici. `null` si aucun plat disponible avec photo.
   */
  getNextDish(restaurantId: string, currentMediaUrl: string | null): Promise<NextApprovalDish | null>
}

interface StatusRow {
  id: string
  restaurant_id: string
  state: StatusState
  auto_generated: boolean
  content: string
  media_url: string | null
}

export function createApprovalRepo(db: SupabaseClient): ApprovalRepo {
  const autoStatusRepo = createAutoStatusRepo(db)

  return {
    async getStatus(statusId, restaurantId) {
      const { data } = await db
        .from('statuses')
        .select('id, restaurant_id, state, auto_generated, content, media_url')
        .eq('id', statusId)
        .eq('restaurant_id', restaurantId)
        .maybeSingle()
      const row = data as StatusRow | null
      if (!row) return null
      return {
        id: row.id,
        restaurantId: row.restaurant_id,
        state: row.state,
        autoGenerated: row.auto_generated,
        content: row.content,
        mediaUrl: row.media_url,
      }
    },

    async approve(statusId) {
      const { data } = await db
        .from('statuses')
        .update({ state: 'scheduled' })
        .eq('id', statusId)
        .eq('state', 'pending_approval')
        .select('id')
      return ((data ?? []) as { id: string }[]).length > 0
    },

    async cancel(statusId) {
      const { data } = await db
        .from('statuses')
        .update({ state: 'canceled', error: 'Refusé par le gérant.' })
        .eq('id', statusId)
        .eq('state', 'pending_approval')
        .select('id')
      return ((data ?? []) as { id: string }[]).length > 0
    },

    async regenerate(statusId, content, mediaUrl) {
      const { data } = await db
        .from('statuses')
        .update({ content, media_url: mediaUrl })
        .eq('id', statusId)
        .eq('state', 'pending_approval')
        .select('id')
      return ((data ?? []) as { id: string }[]).length > 0
    },

    async getNextDish(restaurantId, currentMediaUrl) {
      const dishes = await autoStatusRepo.getPhotoDishes(restaurantId)
      if (dishes.length === 0) return null
      const currentIndex = currentMediaUrl ? dishes.findIndex((d) => d.photoUrl === currentMediaUrl) : -1
      const nextIndex = currentIndex === -1 ? 0 : (currentIndex + 1) % dishes.length
      const dish = dishes[nextIndex]
      return { name: dish.name, price: dish.price, photoUrl: dish.photoUrl, index: nextIndex }
    },
  }
}
