import type { SupabaseClient } from '@supabase/supabase-js'
import type { ChannelPostState } from '@goutatou/db'
import { createAutoStatusRepo } from '../autostatus/repo.js'

export interface ApprovalChannelPostRow {
  id: string
  restaurantId: string
  state: ChannelPostState
  autoGenerated: boolean
  content: string
  mediaUrl: string | null
  /** Numéro du gérant validateur effectif (auto_status_manager_phone ?? contact_phone). Sert au
   * contrôle d'identité : seul ce numéro peut valider (mirror autostatus/approval-repo.ts). Null =
   * non renseigné → on ne verrouille pas (la portée par restaurant + l'id UUID restent les gardes). */
  managerPhone: string | null
}

/** Plat choisi pour une régénération, avec sa position dans la rotation (utilisée comme templateIndex). */
export interface NextChannelApprovalDish {
  name: string
  price: number
  photoUrl: string
  index: number
}

export interface ChannelApprovalRepo {
  /**
   * Lecture SÉCURISÉE : filtre `restaurant_id` dans la requête même (pas de check applicatif
   * après coup) — aucune validation croisée entre restaurants n'est possible. `null` si le post
   * n'existe pas ou appartient à un autre restaurant que celui du canal.
   */
  getPost(postId: string, restaurantId: string): Promise<ApprovalChannelPostRow | null>
  /** Passe en 'scheduled' UNIQUEMENT si l'état courant est 'pending_approval'. Renvoie le succès. */
  approve(postId: string): Promise<boolean>
  /** Passe en 'canceled' + error FR, uniquement depuis 'pending_approval'. */
  cancel(postId: string): Promise<boolean>
  /** Remplace content/media_url, reste 'pending_approval' (garde côté requête, pas seulement processor). */
  regenerate(postId: string, content: string, mediaUrl: string): Promise<boolean>
  /**
   * Plat suivant le plat courant (mediaUrl actuel) dans la rotation des plats disponibles avec
   * photo — même lecture que le flux de génération auto (cf. autochannel/repo.ts, qui délègue déjà
   * à autostatus/repo.ts getPhotoDishes), réutilisée en LECTURE SEULE ici. `null` si aucun plat
   * disponible avec photo.
   */
  getNextDish(restaurantId: string, currentMediaUrl: string | null): Promise<NextChannelApprovalDish | null>
}

interface ChannelPostRow {
  id: string
  restaurant_id: string
  state: ChannelPostState
  auto_generated: boolean
  content: string
  media_url: string | null
  restaurants: { auto_status_manager_phone: string | null; contact_phone: string | null } | null
}

export function createChannelApprovalRepo(db: SupabaseClient): ChannelApprovalRepo {
  const autoStatusRepo = createAutoStatusRepo(db)

  return {
    async getPost(postId, restaurantId) {
      const { data } = await db
        .from('channel_posts')
        .select(
          'id, restaurant_id, state, auto_generated, content, media_url, restaurants(auto_status_manager_phone, contact_phone)',
        )
        .eq('id', postId)
        .eq('restaurant_id', restaurantId)
        .maybeSingle()
      const row = data as ChannelPostRow | null
      if (!row) return null
      return {
        id: row.id,
        restaurantId: row.restaurant_id,
        state: row.state,
        autoGenerated: row.auto_generated,
        content: row.content,
        mediaUrl: row.media_url,
        managerPhone: row.restaurants?.auto_status_manager_phone ?? row.restaurants?.contact_phone ?? null,
      }
    },

    async approve(postId) {
      const { data } = await db
        .from('channel_posts')
        .update({ state: 'scheduled' })
        .eq('id', postId)
        .eq('state', 'pending_approval')
        .select('id')
      return ((data ?? []) as { id: string }[]).length > 0
    },

    async cancel(postId) {
      const { data } = await db
        .from('channel_posts')
        .update({ state: 'canceled', error: 'Refusé par le gérant.' })
        .eq('id', postId)
        .eq('state', 'pending_approval')
        .select('id')
      return ((data ?? []) as { id: string }[]).length > 0
    },

    async regenerate(postId, content, mediaUrl) {
      const { data } = await db
        .from('channel_posts')
        .update({ content, media_url: mediaUrl })
        .eq('id', postId)
        .eq('state', 'pending_approval')
        .select('id')
      return ((data ?? []) as { id: string }[]).length > 0
    },

    async getNextDish(restaurantId, currentMediaUrl) {
      const dishes = await autoStatusRepo.getPhotoDishes(restaurantId)
      if (dishes.length === 0) return null
      const currentIndex = currentMediaUrl ? dishes.findIndex((d) => d.photoUrl === currentMediaUrl) : -1
      const nextIndex = currentIndex === -1 ? 0 : (currentIndex + 1) % dishes.length
      const dish = dishes[nextIndex]
      return { name: dish.name, price: dish.price, photoUrl: dish.photoUrl, index: nextIndex }
    },
  }
}
