import { describe, expect, it, vi } from 'vitest'
import type { SupabaseClient } from '@supabase/supabase-js'
import { createApprovalRepo } from '../src/autostatus/approval-repo.js'

/** Chaînable minimal reproduisant le style thenable de PostgrestFilterBuilder (cf. autostatus-repo.test.ts). */
function makeChain(finalData: unknown) {
  const chain: Record<string, unknown> = {}
  for (const m of ['select', 'eq', 'order', 'update', 'insert']) {
    chain[m] = vi.fn(() => chain)
  }
  chain.maybeSingle = vi.fn(() => Promise.resolve({ data: finalData, error: null }))
  chain.then = (resolve: (v: { data: unknown; error: null }) => unknown) =>
    Promise.resolve({ data: finalData, error: null }).then(resolve)
  return chain
}

describe('createApprovalRepo — getStatus', () => {
  it('filtre id + restaurant_id, mappe les colonnes', async () => {
    const chain = makeChain({
      id: 'st1', restaurant_id: 'r1', state: 'pending_approval',
      auto_generated: true, content: 'Légende', media_url: 'https://x/a.jpg',
      restaurants: { auto_status_manager_phone: '24106871309', contact_phone: '24177000070' },
    })
    const from = vi.fn().mockReturnValue(chain)
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    const status = await repo.getStatus('st1', 'r1')

    expect(status).toEqual({
      id: 'st1', restaurantId: 'r1', state: 'pending_approval',
      autoGenerated: true, content: 'Légende', mediaUrl: 'https://x/a.jpg',
      managerPhone: '24106871309',
    })
    expect(chain.eq).toHaveBeenCalledWith('id', 'st1')
    expect(chain.eq).toHaveBeenCalledWith('restaurant_id', 'r1')
  })

  it('aucune ligne (id inconnu ou autre restaurant) → null', async () => {
    const chain = makeChain(null)
    const from = vi.fn().mockReturnValue(chain)
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    expect(await repo.getStatus('st1', 'r1')).toBeNull()
  })
})

describe('createApprovalRepo — approve/cancel/regenerate', () => {
  it('approve : passe en scheduled, filtre state=pending_approval, succès si ligne retournée', async () => {
    const chain = makeChain([{ id: 'st1' }])
    const from = vi.fn().mockReturnValue(chain)
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    const ok = await repo.approve('st1')

    expect(ok).toBe(true)
    expect(chain.update).toHaveBeenCalledWith({ state: 'scheduled' })
    expect(chain.eq).toHaveBeenCalledWith('id', 'st1')
    expect(chain.eq).toHaveBeenCalledWith('state', 'pending_approval')
  })

  it('approve : aucune ligne mise à jour (déjà traité) → false', async () => {
    const chain = makeChain([])
    const from = vi.fn().mockReturnValue(chain)
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    expect(await repo.approve('st1')).toBe(false)
  })

  it('cancel : passe en canceled avec error FR', async () => {
    const chain = makeChain([{ id: 'st1' }])
    const from = vi.fn().mockReturnValue(chain)
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    const ok = await repo.cancel('st1')

    expect(ok).toBe(true)
    expect(chain.update).toHaveBeenCalledWith({ state: 'canceled', error: 'Refusé par le gérant.' })
    expect(chain.eq).toHaveBeenCalledWith('state', 'pending_approval')
  })

  it('regenerate : remplace content/media_url, reste implicitement pending_approval (pas dans le payload)', async () => {
    const chain = makeChain([{ id: 'st1' }])
    const from = vi.fn().mockReturnValue(chain)
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    const ok = await repo.regenerate('st1', 'Nouvelle légende', 'https://x/b.jpg')

    expect(ok).toBe(true)
    expect(chain.update).toHaveBeenCalledWith({ content: 'Nouvelle légende', media_url: 'https://x/b.jpg' })
    expect(chain.eq).toHaveBeenCalledWith('state', 'pending_approval')
  })
})

describe('createApprovalRepo — getNextDish', () => {
  function dishesChain(rows: unknown) {
    const chain: Record<string, unknown> = {}
    for (const m of ['select', 'eq', 'order']) chain[m] = vi.fn(() => chain)
    chain.then = (resolve: (v: { data: unknown; error: null }) => unknown) =>
      Promise.resolve({ data: rows, error: null }).then(resolve)
    return chain
  }

  it('mediaUrl courant trouvé → renvoie le plat SUIVANT (rotation)', async () => {
    const cats = [{
      position: 1,
      menu_items: [
        { id: 'a', name: 'Poulet', price: 5000, photo_url: 'https://x/a.jpg', available: true, position: 0 },
        { id: 'b', name: 'Poisson', price: 6000, photo_url: 'https://x/b.jpg', available: true, position: 1 },
        { id: 'c', name: 'Nems', price: 2000, photo_url: 'https://x/c.jpg', available: true, position: 2 },
      ],
    }]
    const from = vi.fn().mockReturnValue(dishesChain(cats))
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    const dish = await repo.getNextDish('r1', 'https://x/a.jpg')

    expect(dish).toEqual({ name: 'Poisson', price: 6000, photoUrl: 'https://x/b.jpg', index: 1 })
  })

  it('mediaUrl courant = dernier plat → boucle sur le premier', async () => {
    const cats = [{
      position: 1,
      menu_items: [
        { id: 'a', name: 'Poulet', price: 5000, photo_url: 'https://x/a.jpg', available: true, position: 0 },
        { id: 'b', name: 'Poisson', price: 6000, photo_url: 'https://x/b.jpg', available: true, position: 1 },
      ],
    }]
    const from = vi.fn().mockReturnValue(dishesChain(cats))
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    const dish = await repo.getNextDish('r1', 'https://x/b.jpg')

    expect(dish).toEqual({ name: 'Poulet', price: 5000, photoUrl: 'https://x/a.jpg', index: 0 })
  })

  it('mediaUrl courant absent des plats dispo (ou null) → renvoie le premier', async () => {
    const cats = [{
      position: 1,
      menu_items: [
        { id: 'a', name: 'Poulet', price: 5000, photo_url: 'https://x/a.jpg', available: true, position: 0 },
      ],
    }]
    const from = vi.fn().mockReturnValue(dishesChain(cats))
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    expect(await repo.getNextDish('r1', null)).toEqual({ name: 'Poulet', price: 5000, photoUrl: 'https://x/a.jpg', index: 0 })
    expect(await repo.getNextDish('r1', 'https://x/unknown.jpg')).toEqual({ name: 'Poulet', price: 5000, photoUrl: 'https://x/a.jpg', index: 0 })
  })

  it('aucun plat disponible avec photo → null', async () => {
    const from = vi.fn().mockReturnValue(dishesChain([]))
    const repo = createApprovalRepo({ from } as unknown as SupabaseClient)

    expect(await repo.getNextDish('r1', null)).toBeNull()
  })
})
