import { beforeEach, describe, expect, it, vi } from 'vitest'
import { EMPTY_CART } from '@goutatou/db'
import { createProcessor, type ProcessorDeps } from '../src/processor.js'
import type { BotRepo } from '../src/repo.js'
import type { ChannelApprovalRepo } from '../src/autochannel/approval-repo.js'

const CHAT_ID = '24177000001@s.whatsapp.net'

function replyPayload(id: string, title = 'tap') {
  return {
    messages: [{
      id: 'MSG-CHANNEL-APPROVAL',
      from_me: false,
      type: 'reply',
      chat_id: CHAT_ID,
      from: '24177000009',
      from_name: 'Gérant',
      reply: { type: 'buttons_reply', buttons_reply: { id, title } },
    }],
    channel_id: 'WHAPI-CHAN',
  }
}

describe('processor — validation des posts chaîne (boutons chapp/chrej/chreg/chcan)', () => {
  let repo: BotRepo
  let channelApprovalRepo: ChannelApprovalRepo
  let sendText: ReturnType<typeof vi.fn>
  let sendImage: ReturnType<typeof vi.fn>
  let sendQuickReplies: ReturnType<typeof vi.fn>
  let deps: ProcessorDeps

  function process() {
    return createProcessor(repo, () => ({
      sendText,
      sendImage,
      sendTyping: vi.fn().mockResolvedValue(undefined),
      markAsRead: vi.fn().mockResolvedValue(undefined),
      react: vi.fn().mockResolvedValue(undefined),
      sendLocation: vi.fn().mockResolvedValue({ id: 'OUT-LOC' }),
      sendCatalog: vi.fn().mockResolvedValue({ id: 'OUT-CATALOG' }),
      getOrderItems: vi.fn(),
      sendQuickReplies,
    }), deps)
  }

  beforeEach(() => {
    sendText = vi.fn().mockResolvedValue({ id: 'OUT-TEXT' })
    sendImage = vi.fn().mockResolvedValue({ id: 'OUT-IMG' })
    sendQuickReplies = vi.fn().mockResolvedValue({ id: 'OUT-QR' })

    repo = {
      getChannel: vi.fn().mockResolvedValue({
        channelUuid: 'chan-uuid', restaurantId: 'resto-1', restaurantName: 'Chez Test',
        token: 'tok', driveEnabled: true,
      }),
      getBotContext: vi.fn().mockResolvedValue({
        restaurantName: 'Chez Test', driveEnabled: true, driveSlots: [], menu: { categories: [] },
      }),
      upsertCustomer: vi.fn().mockResolvedValue({ id: 'cust-1' }),
      setOptedOut: vi.fn().mockResolvedValue(undefined),
      setMarketingOptIn: vi.fn().mockResolvedValue(undefined),
      getWheelInfo: vi.fn().mockResolvedValue({ enabled: false, triggerOrders: 5, orderCount: 0 }),
      loadConversation: vi.fn().mockResolvedValue({ state: 'ACCUEIL', cart: EMPTY_CART }),
      saveConversation: vi.fn().mockResolvedValue(undefined),
      createOrder: vi.fn(),
      logMessage: vi.fn().mockResolvedValue(true),
    }

    channelApprovalRepo = {
      getPost: vi.fn(),
      approve: vi.fn(),
      cancel: vi.fn(),
      regenerate: vi.fn(),
      getNextDish: vi.fn(),
    }

    deps = {
      sleep: vi.fn().mockResolvedValue(undefined),
      sendDelayMinMs: 0, sendDelayMaxMs: 0, menuPhotosMax: 8,
      channelApprovalRepo,
    }
  })

  describe('sécurité — post introuvable ou d’un autre restaurant ou manuel', () => {
    it('getPost renvoie null (id inconnu / autre restaurant) → message FR, aucune écriture', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue(null)
      await process()('chan-uuid', replyPayload('chapp:ch-x'))

      expect(channelApprovalRepo.getPost).toHaveBeenCalledWith('ch-x', 'resto-1')
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "Cette validation n'est plus disponible.")
      expect(channelApprovalRepo.approve).not.toHaveBeenCalled()
    })

    it('post existant mais NON auto_generated (manuel) → ignoré avec le même message FR', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: false, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      await process()('chan-uuid', replyPayload('chapp:ch-1'))

      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "Cette validation n'est plus disponible.")
      expect(channelApprovalRepo.approve).not.toHaveBeenCalled()
    })

    it('émetteur ≠ numéro du gérant validateur → notAvailable, aucune écriture', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: '24106871309',
      })
      await process()('chan-uuid', replyPayload('chapp:ch-1'))

      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "Cette validation n'est plus disponible.")
      expect(channelApprovalRepo.approve).not.toHaveBeenCalled()
    })
  })

  describe('approve (chapp:)', () => {
    it('pending_approval → approve() puis confirmation FR', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      channelApprovalRepo.approve = vi.fn().mockResolvedValue(true)
      await process()('chan-uuid', replyPayload('chapp:ch-1', '✅ Valider'))

      expect(channelApprovalRepo.approve).toHaveBeenCalledWith('ch-1')
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "✅ Post chaîne validé — publication à l'heure prévue.")
    })

    it('déjà traité (state != pending_approval) → message FR, approve() non appelé', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'scheduled',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      await process()('chan-uuid', replyPayload('chapp:ch-1'))

      expect(channelApprovalRepo.approve).not.toHaveBeenCalled()
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, 'Ce post chaîne a déjà été traité.')
    })
  })

  describe('reject (chrej:)', () => {
    it('pending_approval → boutons Régénérer/Annuler', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      await process()('chan-uuid', replyPayload('chrej:ch-1'))

      expect(sendQuickReplies).toHaveBeenCalledTimes(1)
      const [to, body, buttons] = sendQuickReplies.mock.calls[0]
      expect(to).toBe(CHAT_ID)
      expect(body).toBe('Que souhaitez-vous faire ?')
      expect(buttons).toEqual([
        { id: 'chreg:ch-1', title: '🔄 Régénérer' },
        { id: 'chcan:ch-1', title: '🚫 Annuler' },
      ])
    })
  })

  describe('regen (chreg:)', () => {
    it('régénère avec le plat suivant, reste pending, renvoie image + Valider/Refuser', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'ancienne légende', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      channelApprovalRepo.getNextDish = vi.fn().mockResolvedValue({
        name: 'Poisson braisé', price: 6000, photoUrl: 'https://x/b.jpg', index: 1,
      })
      channelApprovalRepo.regenerate = vi.fn().mockResolvedValue(true)

      await process()('chan-uuid', replyPayload('chreg:ch-1'))

      expect(channelApprovalRepo.getNextDish).toHaveBeenCalledWith('resto-1', 'https://x/a.jpg')
      expect(channelApprovalRepo.regenerate).toHaveBeenCalledWith(
        'ch-1', expect.stringContaining('Poisson braisé'), 'https://x/b.jpg',
      )
      const [, newContent] = channelApprovalRepo.regenerate.mock.calls[0]
      expect(newContent).not.toBe('ancienne légende')

      expect(sendImage).toHaveBeenCalledWith(CHAT_ID, 'https://x/b.jpg', newContent)
      expect(sendQuickReplies).toHaveBeenCalledTimes(1)
      const [, body, buttons] = sendQuickReplies.mock.calls[0]
      expect(body).toBe('Publier ce post chaîne ?')
      expect(buttons).toEqual([
        { id: 'chapp:ch-1', title: '✅ Valider' },
        { id: 'chrej:ch-1', title: '❌ Refuser' },
      ])
    })

    it('aucun plat disponible avec photo → message FR, pas de regenerate()', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      channelApprovalRepo.getNextDish = vi.fn().mockResolvedValue(null)

      await process()('chan-uuid', replyPayload('chreg:ch-1'))

      expect(channelApprovalRepo.regenerate).not.toHaveBeenCalled()
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, 'Aucun autre plat disponible avec photo pour régénérer.')
    })
  })

  describe('cancel (chcan:)', () => {
    it('pending_approval → cancel() puis confirmation FR', async () => {
      channelApprovalRepo.getPost = vi.fn().mockResolvedValue({
        id: 'ch-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      channelApprovalRepo.cancel = vi.fn().mockResolvedValue(true)

      await process()('chan-uuid', replyPayload('chcan:ch-1'))

      expect(channelApprovalRepo.cancel).toHaveBeenCalledWith('ch-1')
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, '🚫 Post chaîne annulé.')
    })
  })

  describe('non-régression', () => {
    it('id non-approbation chaîne (in:/titre) → toujours routé vers la machine, jamais vers channelApprovalRepo', async () => {
      repo.loadConversation = vi.fn().mockResolvedValue({ state: 'ACCUEIL', cart: EMPTY_CART })
      await process()('chan-uuid', replyPayload('in:menu', 'menu'))

      expect(channelApprovalRepo.getPost).not.toHaveBeenCalled()
      expect(repo.loadConversation).toHaveBeenCalled()
    })

    it('id de validation statut (stapp:/etc.) → jamais routé vers channelApprovalRepo', async () => {
      await process()('chan-uuid', replyPayload('stapp:st-1'))
      expect(channelApprovalRepo.getPost).not.toHaveBeenCalled()
    })

    it('channelApprovalRepo non fourni (deps.channelApprovalRepo undefined) → best-effort, jamais de throw', async () => {
      deps = { sleep: vi.fn().mockResolvedValue(undefined), sendDelayMinMs: 0, sendDelayMaxMs: 0, menuPhotosMax: 8 }
      await expect(process()('chan-uuid', replyPayload('chapp:ch-1'))).resolves.not.toThrow()
      expect(sendText).not.toHaveBeenCalled()
    })

    it('idempotence : message déjà loggé (logMessage renvoie false) → aucun traitement', async () => {
      repo.logMessage = vi.fn().mockResolvedValue(false)
      await process()('chan-uuid', replyPayload('chapp:ch-1'))

      expect(channelApprovalRepo.getPost).not.toHaveBeenCalled()
    })
  })
})
