import { beforeEach, describe, expect, it, vi } from 'vitest'
import { EMPTY_CART } from '@goutatou/db'
import { createProcessor, type ProcessorDeps } from '../src/processor.js'
import type { BotRepo } from '../src/repo.js'
import type { ApprovalRepo } from '../src/autostatus/approval-repo.js'

const CHAT_ID = '24177000001@s.whatsapp.net'

function replyPayload(id: string, title = 'tap') {
  return {
    messages: [{
      id: 'MSG-APPROVAL',
      from_me: false,
      type: 'reply',
      chat_id: CHAT_ID,
      from: '24177000009',
      from_name: 'Gérant',
      reply: { type: 'buttons_reply', buttons_reply: { id, title } },
    }],
    channel_id: 'WHAPI-CHAN',
  }
}

describe('processor — validation des statuts (boutons stapp/strej/streg/stcan)', () => {
  let repo: BotRepo
  let approvalRepo: ApprovalRepo
  let sendText: ReturnType<typeof vi.fn>
  let sendImage: ReturnType<typeof vi.fn>
  let sendQuickReplies: ReturnType<typeof vi.fn>
  let deps: ProcessorDeps

  function process() {
    return createProcessor(repo, () => ({
      sendText,
      sendImage,
      sendTyping: vi.fn().mockResolvedValue(undefined),
      markAsRead: vi.fn().mockResolvedValue(undefined),
      react: vi.fn().mockResolvedValue(undefined),
      sendLocation: vi.fn().mockResolvedValue({ id: 'OUT-LOC' }),
      sendCatalog: vi.fn().mockResolvedValue({ id: 'OUT-CATALOG' }),
      getOrderItems: vi.fn(),
      sendQuickReplies,
    }), deps)
  }

  beforeEach(() => {
    sendText = vi.fn().mockResolvedValue({ id: 'OUT-TEXT' })
    sendImage = vi.fn().mockResolvedValue({ id: 'OUT-IMG' })
    sendQuickReplies = vi.fn().mockResolvedValue({ id: 'OUT-QR' })

    repo = {
      getChannel: vi.fn().mockResolvedValue({
        channelUuid: 'chan-uuid', restaurantId: 'resto-1', restaurantName: 'Chez Test',
        token: 'tok', driveEnabled: true,
      }),
      getBotContext: vi.fn().mockResolvedValue({
        restaurantName: 'Chez Test', driveEnabled: true, driveSlots: [], menu: { categories: [] },
      }),
      upsertCustomer: vi.fn().mockResolvedValue({ id: 'cust-1' }),
      setOptedOut: vi.fn().mockResolvedValue(undefined),
      setMarketingOptIn: vi.fn().mockResolvedValue(undefined),
      getWheelInfo: vi.fn().mockResolvedValue({ enabled: false, triggerOrders: 5, orderCount: 0 }),
      loadConversation: vi.fn().mockResolvedValue({ state: 'ACCUEIL', cart: EMPTY_CART }),
      saveConversation: vi.fn().mockResolvedValue(undefined),
      createOrder: vi.fn(),
      logMessage: vi.fn().mockResolvedValue(true),
    }

    approvalRepo = {
      getStatus: vi.fn(),
      approve: vi.fn(),
      cancel: vi.fn(),
      regenerate: vi.fn(),
      getNextDish: vi.fn(),
    }

    deps = {
      sleep: vi.fn().mockResolvedValue(undefined),
      sendDelayMinMs: 0, sendDelayMaxMs: 0, menuPhotosMax: 8,
      approvalRepo,
    }
  })

  describe('sécurité — statut introuvable ou d’un autre restaurant ou manuel', () => {
    it('getStatus renvoie null (id inconnu / autre restaurant) → message FR, aucune écriture', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue(null)
      await process()('chan-uuid', replyPayload('stapp:st-x'))

      expect(approvalRepo.getStatus).toHaveBeenCalledWith('st-x', 'resto-1')
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "Cette validation n'est plus disponible.")
      expect(approvalRepo.approve).not.toHaveBeenCalled()
    })

    it('statut existant mais NON auto_generated (manuel) → ignoré avec le même message FR', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: false, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      await process()('chan-uuid', replyPayload('stapp:st-1'))

      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "Cette validation n'est plus disponible.")
      expect(approvalRepo.approve).not.toHaveBeenCalled()
    })
  })

  describe('approve (stapp:)', () => {
    it('pending_approval → approve() puis confirmation FR', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      approvalRepo.approve = vi.fn().mockResolvedValue(true)
      await process()('chan-uuid', replyPayload('stapp:st-1', '✅ Valider'))

      expect(approvalRepo.approve).toHaveBeenCalledWith('st-1')
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, "✅ Statut validé — publication à l'heure prévue.")
    })

    it('déjà traité (state != pending_approval) → message FR, approve() non appelé', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'scheduled',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      await process()('chan-uuid', replyPayload('stapp:st-1'))

      expect(approvalRepo.approve).not.toHaveBeenCalled()
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, 'Ce statut a déjà été traité.')
    })
  })

  describe('reject (strej:)', () => {
    it('pending_approval → boutons Régénérer/Annuler', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      await process()('chan-uuid', replyPayload('strej:st-1'))

      expect(sendQuickReplies).toHaveBeenCalledTimes(1)
      const [to, body, buttons] = sendQuickReplies.mock.calls[0]
      expect(to).toBe(CHAT_ID)
      expect(body).toBe('Que souhaitez-vous faire ?')
      expect(buttons).toEqual([
        { id: 'streg:st-1', title: '🔄 Régénérer' },
        { id: 'stcan:st-1', title: '🚫 Annuler' },
      ])
    })
  })

  describe('regen (streg:)', () => {
    it('régénère avec le plat suivant, reste pending, renvoie image + Valider/Refuser', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'ancienne légende', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      approvalRepo.getNextDish = vi.fn().mockResolvedValue({
        name: 'Poisson braisé', price: 6000, photoUrl: 'https://x/b.jpg', index: 1,
      })
      approvalRepo.regenerate = vi.fn().mockResolvedValue(true)

      await process()('chan-uuid', replyPayload('streg:st-1'))

      expect(approvalRepo.getNextDish).toHaveBeenCalledWith('resto-1', 'https://x/a.jpg')
      expect(approvalRepo.regenerate).toHaveBeenCalledWith(
        'st-1', expect.stringContaining('Poisson braisé'), 'https://x/b.jpg',
      )
      // Contenu changé : plus la même légende, contient bien le nouveau plat/prix.
      const [, newContent] = approvalRepo.regenerate.mock.calls[0]
      expect(newContent).not.toBe('ancienne légende')

      expect(sendImage).toHaveBeenCalledWith(CHAT_ID, 'https://x/b.jpg', newContent)
      expect(sendQuickReplies).toHaveBeenCalledTimes(1)
      const [, body, buttons] = sendQuickReplies.mock.calls[0]
      expect(body).toBe('Publier ce statut ?')
      expect(buttons).toEqual([
        { id: 'stapp:st-1', title: '✅ Valider' },
        { id: 'strej:st-1', title: '❌ Refuser' },
      ])
    })

    it('aucun plat disponible avec photo → message FR, pas de regenerate()', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      approvalRepo.getNextDish = vi.fn().mockResolvedValue(null)

      await process()('chan-uuid', replyPayload('streg:st-1'))

      expect(approvalRepo.regenerate).not.toHaveBeenCalled()
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, 'Aucun autre plat disponible avec photo pour régénérer.')
    })
  })

  describe('cancel (stcan:)', () => {
    it('pending_approval → cancel() puis confirmation FR', async () => {
      approvalRepo.getStatus = vi.fn().mockResolvedValue({
        id: 'st-1', restaurantId: 'resto-1', state: 'pending_approval',
        autoGenerated: true, content: 'x', mediaUrl: 'https://x/a.jpg', managerPhone: null,
      })
      approvalRepo.cancel = vi.fn().mockResolvedValue(true)

      await process()('chan-uuid', replyPayload('stcan:st-1'))

      expect(approvalRepo.cancel).toHaveBeenCalledWith('st-1')
      expect(sendText).toHaveBeenCalledWith(CHAT_ID, '🚫 Statut annulé.')
    })
  })

  describe('non-régression', () => {
    it('id non-approbation (in:/titre) → toujours routé vers la machine, jamais vers approvalRepo', async () => {
      repo.loadConversation = vi.fn().mockResolvedValue({ state: 'ACCUEIL', cart: EMPTY_CART })
      await process()('chan-uuid', replyPayload('in:menu', 'menu'))

      expect(approvalRepo.getStatus).not.toHaveBeenCalled()
      expect(repo.loadConversation).toHaveBeenCalled()
    })

    it('approvalRepo non fourni (deps.approvalRepo undefined) → best-effort, jamais de throw', async () => {
      deps = { sleep: vi.fn().mockResolvedValue(undefined), sendDelayMinMs: 0, sendDelayMaxMs: 0, menuPhotosMax: 8 }
      await expect(process()('chan-uuid', replyPayload('stapp:st-1'))).resolves.not.toThrow()
      expect(sendText).not.toHaveBeenCalled()
    })

    it('idempotence : message déjà loggé (logMessage renvoie false) → aucun traitement', async () => {
      repo.logMessage = vi.fn().mockResolvedValue(false)
      await process()('chan-uuid', replyPayload('stapp:st-1'))

      expect(approvalRepo.getStatus).not.toHaveBeenCalled()
    })
  })
})
